name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set Permissions for SSH Key
      run: chmod 600 ${{ secrets.EC2_SSH_KEY }}

    - name: Restart Nginx Server
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo systemctl restart nginx
        debug: true
